//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class myProjectEntities : DbContext
    {
        public myProjectEntities()
            : base("name=myProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Dish> Dishes { get; set; }
        public virtual DbSet<EventExtension> EventExtensions { get; set; }
        public virtual DbSet<EventPacket> EventPackets { get; set; }
        public virtual DbSet<EventsType> EventsTypes { get; set; }
        public virtual DbSet<ExtraToOrder> ExtraToOrders { get; set; }
        public virtual DbSet<OrderArchive> OrderArchives { get; set; }
        public virtual DbSet<OrderDish> OrderDishes { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Recommendation> Recommendations { get; set; }
        public virtual DbSet<StatusDose> StatusDoses { get; set; }
    
        public virtual ObjectResult<trybracha_Result> trybracha()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<trybracha_Result>("trybracha");
        }
    }
}
